name: Build Flutter Apps

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [apk, appbundle, ios, linux, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (Android)
        if: matrix.platform == 'apk'
        run: flutter build apk --release

      - name: Build AppBundle (Android Play Store)
        if: matrix.platform == 'appbundle'
        run: flutter build appbundle --release

      - name: Build iOS
        if: matrix.platform == 'ios'
        run: flutter build ios --release --no-codesign

      - name: Build Linux
        if: matrix.platform == 'linux'
        run: flutter build linux --release

      - name: Build Windows
        if: matrix.platform == 'windows'
        run: flutter build windows --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-build
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/bundle/release/*.aab
            build/ios/iphoneos/*.app
            build/linux/x64/release/bundle/*
            build/windows/x64/runner/Release/*
