name: Build Flutter Apps

on:
  push:
    branches:
      - main

jobs:
  setup:
    name: Setup Flutter & Dependencies
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Extract version
        id: extract_version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Upload source & dependencies
        uses: actions/upload-artifact@v4
        with:
          name: source-with-deps
          path: |
            .
            !build/
            !.git/

  android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: source-with-deps
          path: .

      - run: flutter build apk --release
      - run: flutter build appbundle --release

      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk knock_knock-${{ needs.setup.outputs.version }}.apk

      - name: Rename AAB
        run: mv build/app/outputs/bundle/release/app-release.aab knock_knock-${{ needs.setup.outputs.version }}.aab

      - uses: actions/upload-artifact@v4
        with:
          name: android
          path: |
            knock_knock-${{ needs.setup.outputs.version }}.apk
            knock_knock-${{ needs.setup.outputs.version }}.aab

  ios:
    name: Build iOS
    runs-on: macos-latest
    needs: setup
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: source-with-deps
          path: .

      - run: flutter build ios --release --no-codesign

      - name: Package iOS app
        run: |
          cd build/ios/iphoneos
          zip -r knock_knock-${{ needs.setup.outputs.version }}.zip *.app

      - uses: actions/upload-artifact@v4
        with:
          name: ios
          path: build/ios/iphoneos/knock_knock-${{ needs.setup.outputs.version }}.zip

  linux:
    name: Build Linux
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: source-with-deps
          path: .

      - run: sudo apt-get update && sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - run: flutter build linux --release

      - name: Package Linux app
        run: |
          cd build/linux/x64/release/bundle
          zip -r knock_knock-${{ needs.setup.outputs.version }}.zip *

      - uses: actions/upload-artifact@v4
        with:
          name: linux
          path: build/linux/x64/release/bundle/knock_knock-${{ needs.setup.outputs.version }}.zip

  windows:
    name: Build Windows
    runs-on: windows-latest
    needs: setup
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: source-with-deps
          path: .

      - run: flutter build windows --release

      - name: Package Windows app
        run: |
          cd build/windows/x64/runner/Release
          powershell Compress-Archive * ../../../../knock_knock-${{ needs.setup.outputs.version }}.zip

      - uses: actions/upload-artifact@v4
        with:
          name: windows
          path: build/knock_knock-${{ needs.setup.outputs.version }}.zip

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [setup, android, ios, linux, windows] # wait for all builds
    steps:
      - name: Download Android artifacts
        uses: actions/download-artifact@v4
        with:
          name: android
          path: dist

      - name: Download iOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: ios
          path: dist

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux
          path: dist

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.setup.outputs.version }}
          name: Knock Knock v${{ needs.setup.outputs.version }}
          draft: false
          prerelease: false
          files: dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
